sudo: required
dist: xenial
addons:
  apt:
    packages:
    - kpartx
    - coreutils
    - qemu-user-static
    - zip
script:
  - sudo ./build.sh
before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) *.zip
deploy:
  provider: releases
  api_key:
    secure: "FtSdIUM2NmYfxEsPR8Bkt8OCAodE6gSIOYwZhV4xxEr9uZl7LbsN8dL9Oa3mfBC0O/VV0/wSPfIPSoaMDMuLaxlUrkSlYHWPhGqUMfKlb5J3gNlnuNnOJFXaMqCdn/NZjsRSq20dqXFfQIz/TTWGfTmegsc5uC62OBoz+OZmr/oiug4xO/Nzlw1pulS4wW7wHDAhy+ui9J43vQSHiJvvLSmGA6c6HQsSk+0AExXHOXrQj1Pcya9VnV2q3TJhVPz3NsKIP3i7GA52bmy0NxKc4/GWNdMraMBOA0tzCxpyvOJFJLxgJGsvA4M/GJZoYVgTAaNyjj8O0LFjRD8n4gOOUygSpkx2YzEwTEpAASpF7DrJZJy6MNv79zyjfm/bIYj0vvRDxU0UWNn54MYfffyFOcM7cJcIYdc6EU4fPfaxmtSKY3BCuSnLZIOY8MD8qUn9FmBxqccO8/jGiiERWt52+NDxwrQFikpzJMf29L9zRJPHrLC7mE2c97bO2OoTApfvBGR9kHLLnQX3oUFz7vpZtT+5PA/HBQfR17+BSx4eSgDmF5IrTyiY3KlFs9tZ8HpPuSkDQYl1lQhg1Iib1l3O0CbnDFlsuFuhUPOGV/RJw5la5e6D4quwpr6mxeUwxMQyEyTKNoRcAcArT9oy6gZXYBRRbQTXci+/6gL6gYAV4TI="
  file: "bc-raspbian-*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
