sudo: required
os: linux
arch: arm64
dist: bionic

env:
  matrix:
    - NAME=bc-raspbian-buster-lite
      URL=http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2020-02-14/2020-02-13-raspbian-buster-lite.zip
      SHA256=12ae6e17bf95b6ba83beca61e7394e7411b45eba7e6a520f434b0748ea7370e8

    - NAME=bc-raspbian-buster
      URL=http://downloads.raspberrypi.org/raspbian/images/raspbian-2020-02-14/2020-02-13-raspbian-buster.zip
      SHA256=a82ed4139dfad31c3167e60e943bcbe28c404d1858f4713efe5530c08a419f50

addons:
  apt:
    packages:
    - kpartx
    - coreutils
    - qemu-user-static
    - zip
    - unzip
    - binfmt-support
    - openssl
    - systemd-container
    - parted

script:
  - sudo ./build.sh

before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) *.zip

deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file: "bc-raspbian-*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
