sudo: required
dist: bionic

env:
  matrix:
    - NAME=hio-raspbian-buster-lite
      URL=https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-lite.zip
      SHA256=d49d6fab1b8e533f7efc40416e98ec16019b9c034bc89c59b83d0921c2aefeef

    - NAME=hio-raspbian-buster-desktop
      URL=https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-01-12/2021-01-11-raspios-buster-armhf.zip
      SHA256=cb1efa778f3a4effda7bf6f622e8e8e779f5303ac77ac8c558061aece9020fe6

addons:
  apt:
    packages:
    - kpartx
    - coreutils
    - qemu-user-static
    - zip
    - unzip
    - binfmt-support
    - openssl
    - systemd-container
    - parted

script:
  - sudo ./build.sh

before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) *.zip

deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file: "hio-raspbian-*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
