sudo: required
dist: bionic
addons:
  apt:
    packages:
    - kpartx
    - coreutils
    - qemu-user-static
    - zip
    - unzip
    - binfmt-support
    - openssl
script:
  - sudo ./build.sh
before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) *.zip
deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file: "bc-raspbian-*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
